Environment=dev
executionMode=local
browser=chrome
headLess=Y
application=anesthesiaprogress
platform=meridian
status=draft
sleepTime=500
timeOut=19
sleepEnabled=true
BrowserStack=N
userflow=publisher_userflow