fpj=https://prime-dev:prime-dev@meridian-fpj-draft.dev.prime.pubfactory.com/
tsir=https://prime-dev:prime-dev@meridian-tscir-draft.dev.prime.pubfactory.com/
anesthesiaprogress=https://prime-dev:prime-dev@meridian-anesthesiaprogress-draft.dev.prime.pubfactory.com/
baseURI_Search=http://prime-search.dev.prime.pubfactory.net
baseURI_Content=http://prime-content.dev.prime.pubfactory.net
baseURI_Authentication=http://prime-authentication.dev.prime.pubfactory.net