
name: APISanityCheck.yml
    
on:
  workflow_dispatch:
    inputs:
      gitcommitId:
        required: true
        description: "get git commit Id from prime-frontend"
        type: string
        default: ''
      jobId:
        required: true
        description: "get job Id from prime-frontend"
        type: string
        default: ''
jobs:
  build:

    runs-on: ${{ (github.ref_name == 'uat') && fromJSON('["self-hosted","uat"]') || (github.ref_name == 'prod') && fromJSON('["self-hosted","prod"]') || fromJSON('["self-hosted","dev"]') }}

    steps:


    - uses: actions/checkout@v3
      id: checkout-gitrepo

      
    - name: Navigating to chromedriver and making it executable
      id: chromedriver-executable
      run: |
          ls -l
          pwd
          cd /opt/actions-runner/_work/qa-prime-api/qa-prime-api/src/test/resources
          chmod +x chromedriver

    - name: Clean and Install Dependencies
      run: mvn clean install -U -DskipTests
      
    - name: Build with Maven
      id: run-test-case
      run: |
        set -o pipefail
        mvn test -DsuiteXmlFile=APITestsPrimeConfig.xml -DEnvironment=dev -Dbrowser=chrome | tee test-results.log
        EXIT_CODE=${PIPESTATUS[0]}
        exit $EXIT_CODE
      #run: mvn test -DsuiteXmlFile=APITestsPrimeConfig.xml  -DEnvironment=dev -Dbrowser=chrome | tee test-results.log

    - name: Extract Brief Test Report
      if: always()
      run: |
        {
          echo "📌 **Failed Tests Summary:**"
          grep -E "Tests run:.*Failures: [1-9]+" test-results.log || echo "✅ No Test Failures Found"
        } > test-failures-summary.txt

          echo "FAILURE_SUMMARY=$(cat test-failures-summary.txt | sed ':a;N;$!ba;s/\n/\\n/g')" >> $GITHUB_ENV

    - name: Extract and Print Detailed logs Test Failures
      if: always()
      run: |
        {
          echo "📌 **Failed Tests Summary:**"
          grep -E "Tests run:.*Failures: [1-9]+" test-results.log || echo "✅ No Test Failures Found"

          echo ""
          echo "⚠️ **Failed Test Cases:**"
          grep -E "<<< FAILURE!|<<< ERROR!" test-results.log || echo "✅ No Test Cases Failed"

          echo ""
          echo "🔍 **Assertion Errors & Stacktrace Snippets:**"
          grep -A 5 -E "(Failure!|AssertionError|expected:.*but was:|at .*Test\()" test-results.log || echo "✅ No Assertions Failed"
        } 

    - name: Send ${{ job.status }} message to #qa-prime-integration room
      if: always()
      uses: act10ns/slack@v2.0.0
      with:
         webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
         status: ${{ job.status }}
         steps: ${{ toJson(steps) }}
         channel: '#qa-prime-integration'
         message: |
            *Build Status*: *${{ job.status }}*.
            *Environment: DEV*.
            Git commit ID: ${{ inputs.gitcommitId }}.
            Prime-frontend job: https://github.com/pubfactory/prime-frontend/actions/runs/${{ inputs.jobId }}

            *Test Failures Summary*:
            ```
            ${{ env.FAILURE_SUMMARY }}
            ```
              env:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
