name: APITests.yml
    
on:
  workflow_dispatch:
    inputs:
      gitcommitId:
        required: true
        description: "get git commit Id from prime-frontend"
        type: string
        default: ''
      jobId:
        required: true
        description: "get job Id from prime-frontend"
        type: string
        default: ''
jobs:
  build:

    runs-on: ${{ (github.ref_name == 'uat') && fromJSON('["self-hosted","uat"]') || (github.ref_name == 'prod') && fromJSON('["self-hosted","prod"]') || fromJSON('["self-hosted","dev"]') }}

    steps:


    - uses: actions/checkout@v3
      id: checkout-gitrepo
      
    - name: Navigating to chromedriver and making it executable
      id: chromedriver-executable
      run: |
          ls -l
          pwd
          cd /opt/actions-runner/_work/qa-prime-e2e/qa-prime-e2e/src/test/resources
          chmod +x chromedriver

    - name: Clean and Install Dependencies
      run: mvn clean install -U -DskipTests
      
    - name: Build with Maven
      id: run-test-case
      run: mvn test -DsuiteXmlFile=UserFlowsPrimeConfig.xml  -DEnvironment=dev -Dbrowser=chrome

    - name: Get Allure history
      uses: actions/checkout@v2
      id: allure-history
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: /tmp/gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
          allure_results: target/allure-results
          gh_pages: /tmp/gh-pages
          allure_report: allure-report
          allure_history: allure-history

    - name: Deploy report to Github Pages
      id: gh-pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
        keep_files: true

    - name: Send ${{ job.status }} message to #qa-prime-integration room
      if: always()
      uses: act10ns/slack@v2.0.0
      with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#qa-prime-integration'
          message: "*Build Status*: *${{ job.status }}*.\n*Environment:DEV*.\nAllure report URL is: https://pubfactory.github.io/qa-prime-e2e/${{ github.run_number }}\nGit commit ID is: ${{ inputs.gitcommitId }}.\nPrime-frontend job is: https://github.com/pubfactory/prime-frontend/actions/runs/${{ inputs.jobId }}"
                  
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
          
    

   
