# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: UserFlows.yml
    
on:
  workflow_dispatch:
    inputs:
      gitcommitId:
        required: true
        description: "get git commit Id from prime-frontend"
        type: string
        default: ''
      jobId:
        required: true
        description: "get job Id from prime-frontend"
        type: string
        default: ''
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      id: checkout-gitrepo
    - name: Set up JDK 8
      id: install-java
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Install Google Chrome
      uses: browser-actions/setup-chrome@latest
      id: install-chrome
    - name: Navigating to chromedriver and making it executable
      id: chromedriver-executable
      run: |
          cd /home/runner/work/qa-prime-e2e/qa-prime-e2e/src/test/resources
          chmod +x chromedriver
    - name: Build with Maven
      id: run-test-case
      run: mvn test -DsuiteXmlFile=UserFlowsPrimeConfig.xml  -DEnvironment=dev -Dbrowser=chrome

    - name: Get Allure history
      uses: actions/checkout@v2
      id: allure-history
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          
    - name: Deploy report to Github Pages
      id: gh-pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
        keep_files: true
        
    - name: Collect Test Results
      run: |
          PASSED=$(grep -c 'passed' allure-results/*.json || echo 0)
          FAILED=$(grep -c 'failed' allure-results/*.json || echo 0)
          TOTAL=$((PASSED + FAILED))
          echo "PASSED=$PASSED" >> $GITHUB_ENV
          echo "FAILED=$FAILED" >> $GITHUB_ENV
          echo "TOTAL=$TOTAL" >> $GITHUB_ENV
      id: collect_results

    - name: Send ${{ job.status }} message to #qa-prime-integration room
      if: always()
      env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PASSED: ${{ env.PASSED }}
          FAILED: ${{ env.FAILED }}
          TOTAL: ${{ env.TOTAL }}
      run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "Test Results Summary",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "🚀 *Test Results Summary*:\n*Total Tests*: '"${TOTAL}"'\n*Passed*: '"${PASSED}"'\n*Failed*: '"${FAILED}"'\n\n🔗 *Allure Report*: <https://pubfactory.github.io/qa-prime-e2e/${{ github.run_number }}|View Report>\nGit commit ID is: ${{ inputs.gitcommitId }}.\nPrime-frontend job is: https://github.com/pubfactory/prime-frontend/actions/runs/${{ inputs.jobId }}"
                }
              }
            ]
          }' $SLACK_WEBHOOK_URL
        

    
